apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: amdp-registry.skala-ai.com/skala26a-cloud/team3-main-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: jwt-secret
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: kafka-servers
            - name: QUEUE_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: queue-server-url
            - name: CORS_SERVER_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: cors-server-origin
            - name: CORS_SERVER_ORIGIN_SWAGGER
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: cors-server-origin-swagger
            - name: APP_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: app-server-url
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: ddl-auto
